//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoPlus.Interpreter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoPlus.Interpreter.Resources.DisplayValues", typeof(DisplayValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Results.
        /// </summary>
        internal static string Debug_Caption {
            get {
                return ResourceManager.GetString("Debug_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Message:.
        /// </summary>
        internal static string Debug_Intro {
            get {
                return ResourceManager.GetString("Debug_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Details:.
        /// </summary>
        internal static string Debug_TemplateDetails {
            get {
                return ResourceManager.GetString("Debug_TemplateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occured while attempting to build the abstract syntax tree for the template:.
        /// </summary>
        internal static string Exception_AST {
            get {
                return ResourceManager.GetString("Exception_AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template AST Error.
        /// </summary>
        internal static string Exception_ASTTitle {
            get {
                return ResourceManager.GetString("Exception_ASTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Model Building Error.
        /// </summary>
        internal static string Exception_BuildModelTitle {
            get {
                return ResourceManager.GetString("Exception_BuildModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Exception_CategoryIntro {
            get {
                return ResourceManager.GetString("Exception_CategoryIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Code Generation Error.
        /// </summary>
        internal static string Exception_CodeGenerationTitle {
            get {
                return ResourceManager.GetString("Exception_CodeGenerationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: Content.
        /// </summary>
        internal static string Exception_ContentLocation {
            get {
                return ResourceManager.GetString("Exception_ContentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} item could not be added to the solution..
        /// </summary>
        internal static string Exception_CouldNotAddItem {
            get {
                return ResourceManager.GetString("Exception_CouldNotAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} item could not be deleted from the solution..
        /// </summary>
        internal static string Exception_CouldNotDeleteItem {
            get {
                return ResourceManager.GetString("Exception_CouldNotDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Message:.
        /// </summary>
        internal static string Exception_InnerMessageIntro {
            get {
                return ResourceManager.GetString("Exception_InnerMessageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of  {0} could not be obtained because it is not related to node {1} or any of its parents..
        /// </summary>
        internal static string Exception_InvalidCollectionContext {
            get {
                return ResourceManager.GetString("Exception_InvalidCollectionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model context could not be switched to {0} because {1} is not related to node {2} or any of its parents..
        /// </summary>
        internal static string Exception_InvalidModelContext {
            get {
                return ResourceManager.GetString("Exception_InvalidModelContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a property called {1}, the value {2} could not be assigned..
        /// </summary>
        internal static string Exception_InvalidPropertyAssignment {
            get {
                return ResourceManager.GetString("Exception_InvalidPropertyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        internal static string Exception_LineNumberIntro {
            get {
                return ResourceManager.GetString("Exception_LineNumberIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Context Node:.
        /// </summary>
        internal static string Exception_ModelContextIntro {
            get {
                return ResourceManager.GetString("Exception_ModelContextIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Item ID:.
        /// </summary>
        internal static string Exception_ModelIdIntro {
            get {
                return ResourceManager.GetString("Exception_ModelIdIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Item Name:.
        /// </summary>
        internal static string Exception_ModelNameIntro {
            get {
                return ResourceManager.GetString("Exception_ModelNameIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the MySQL database {0} on server {1}..
        /// </summary>
        internal static string Exception_MySQLConnection {
            get {
                return ResourceManager.GetString("Exception_MySQLConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema collection {0} could not be loaded from the MySQL database {1}..
        /// </summary>
        internal static string Exception_MySQLSchemaLoad {
            get {
                return ResourceManager.GetString("Exception_MySQLSchemaLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content could be produced for {0} since none is specified for this template..
        /// </summary>
        internal static string Exception_NoContent {
            get {
                return ResourceManager.GetString("Exception_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node:.
        /// </summary>
        internal static string Exception_NodeIntro {
            get {
                return ResourceManager.GetString("Exception_NodeIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output could be produced for {0} since none is specified for this template..
        /// </summary>
        internal static string Exception_NoOutput {
            get {
                return ResourceManager.GetString("Exception_NoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: Output.
        /// </summary>
        internal static string Exception_OutputLocation {
            get {
                return ResourceManager.GetString("Exception_OutputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occured while attempting to parse the template:.
        /// </summary>
        internal static string Exception_Parsing {
            get {
                return ResourceManager.GetString("Exception_Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Parsing Error.
        /// </summary>
        internal static string Exception_ParsingTitle {
            get {
                return ResourceManager.GetString("Exception_ParsingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property {0} did not correspond to {1} or any of its parents, no value could be retrieved..
        /// </summary>
        internal static string Exception_PropertyNotFound {
            get {
                return ResourceManager.GetString("Exception_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution:.
        /// </summary>
        internal static string Exception_SolutionIntro {
            get {
                return ResourceManager.GetString("Exception_SolutionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Database  {0} not found in the following list of databases: {1}..
        /// </summary>
        internal static string Exception_SourceDbNotFound {
            get {
                return ResourceManager.GetString("Exception_SourceDbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to SQLServer {0}..
        /// </summary>
        internal static string Exception_SourceDbServerConnection {
            get {
                return ResourceManager.GetString("Exception_SourceDbServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source xml file {0} not found or is empty..
        /// </summary>
        internal static string Exception_SourceXmlMissing {
            get {
                return ResourceManager.GetString("Exception_SourceXmlMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name:.
        /// </summary>
        internal static string Exception_TemplateIntro {
            get {
                return ResourceManager.GetString("Exception_TemplateIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occured while attempting to interpret a template:.
        /// </summary>
        internal static string Exception_TemplateProcessing {
            get {
                return ResourceManager.GetString("Exception_TemplateProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Error.
        /// </summary>
        internal static string Exception_TemplateTitle {
            get {
                return ResourceManager.GetString("Exception_TemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: This expression could not be evaluated at this breakpoint..
        /// </summary>
        internal static string Exception_WatchExpression {
            get {
                return ResourceManager.GetString("Exception_WatchExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter for the Find method could not be parsed into a Guid..
        /// </summary>
        internal static string Message_InterpreterBadFindParameter {
            get {
                return ResourceManager.GetString("Message_InterpreterBadFindParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content parse error at line: {0}, column: {1}, message: {2}.
        /// </summary>
        internal static string Message_TemplateContentParseError {
            get {
                return ResourceManager.GetString("Message_TemplateContentParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property called {0} could not be matched to a corresponding template..
        /// </summary>
        internal static string Message_TemplateNotFoundError {
            get {
                return ResourceManager.GetString("Message_TemplateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output parse error at line: {0}, column: {1}, message: {2}.
        /// </summary>
        internal static string Message_TemplateOutputParseError {
            get {
                return ResourceManager.GetString("Message_TemplateOutputParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} does not correspond to a declared parameter in the template {1}..
        /// </summary>
        internal static string Message_TemplateParameterNotFoundError {
            get {
                return ResourceManager.GetString("Message_TemplateParameterNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters {0} do not correspond to declared parameters in the template {1}..
        /// </summary>
        internal static string Message_TemplateParametersNotFoundError {
            get {
                return ResourceManager.GetString("Message_TemplateParametersNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} is already declared..
        /// </summary>
        internal static string Message_TemplateVariableAlreadyDeclared {
            get {
                return ResourceManager.GetString("Message_TemplateVariableAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} could not be declared since it conflicts with a defined keyword..
        /// </summary>
        internal static string Message_TemplateVariableConflict {
            get {
                return ResourceManager.GetString("Message_TemplateVariableConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9_][a-zA-Z0-9&amp; _-]*[a-zA-Z0-9&amp;_-]$.
        /// </summary>
        internal static string Regex_DbName {
            get {
                return ResourceManager.GetString("Regex_DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9_][a-zA-Z0-9 -._]*[a-zA-Z0-9_]$.
        /// </summary>
        internal static string Regex_FileName {
            get {
                return ResourceManager.GetString("Regex_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9_.][a-zA-Z0-9 :\\._]*[a-zA-Z0-9_]$.
        /// </summary>
        internal static string Regex_FilePath {
            get {
                return ResourceManager.GetString("Regex_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z_][a-zA-Z0-9 _-]*[a-zA-Z0-9_-]$.
        /// </summary>
        internal static string Regex_LooseName {
            get {
                return ResourceManager.GetString("Regex_LooseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z_-][a-zA-Z0-9_-]*$.
        /// </summary>
        internal static string Regex_Name {
            get {
                return ResourceManager.GetString("Regex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9_][a-zA-Z0-9_\.]*[a-zA-Z0-9_]$.
        /// </summary>
        internal static string Regex_Namespace {
            get {
                return ResourceManager.GetString("Regex_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9_-][a-zA-Z0-9\\_-]*$.
        /// </summary>
        internal static string Regex_PathName {
            get {
                return ResourceManager.GetString("Regex_PathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-zA-Z0-9_]+.
        /// </summary>
        internal static string Regex_Word {
            get {
                return ResourceManager.GetString("Regex_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CONFIG section in the template file is malformed, and/or does not contain NAME, TIER, or NODE information..
        /// </summary>
        internal static string Template_BadConfiguration {
            get {
                return ResourceManager.GetString("Template_BadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CONTENTsection in the template file is malformed, and/or does not contain content in the expected template language..
        /// </summary>
        internal static string Template_BadContent {
            get {
                return ResourceManager.GetString("Template_BadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OUTPUTsection in the template file is malformed, and/or does not contain content in the expected template language..
        /// </summary>
        internal static string Template_BadOutput {
            get {
                return ResourceManager.GetString("Template_BadOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called By:.
        /// </summary>
        internal static string Template_CalledByIntro {
            get {
                return ResourceManager.GetString("Template_CalledByIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates Called:.
        /// </summary>
        internal static string Template_CallIntro {
            get {
                return ResourceManager.GetString("Template_CallIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified by this template was not found, please save the template to a file..
        /// </summary>
        internal static string Template_MissingFile {
            get {
                return ResourceManager.GetString("Template_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string TemplateNode_AddStatement {
            get {
                return ResourceManager.GetString("TemplateNode_AddStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break.
        /// </summary>
        internal static string TemplateNode_BreakStatement {
            get {
                return ResourceManager.GetString("TemplateNode_BreakStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case.
        /// </summary>
        internal static string TemplateNode_CaseClause {
            get {
                return ResourceManager.GetString("TemplateNode_CaseClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condition.
        /// </summary>
        internal static string TemplateNode_CaseCondition {
            get {
                return ResourceManager.GetString("TemplateNode_CaseCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string TemplateNode_ClearStatement {
            get {
                return ResourceManager.GetString("TemplateNode_ClearStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        internal static string TemplateNode_ContinueStatement {
            get {
                return ResourceManager.GetString("TemplateNode_ContinueStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current item assignment.
        /// </summary>
        internal static string TemplateNode_CurrentItemAssignment {
            get {
                return ResourceManager.GetString("TemplateNode_CurrentItemAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug.
        /// </summary>
        internal static string TemplateNode_DebugStatement {
            get {
                return ResourceManager.GetString("TemplateNode_DebugStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string TemplateNode_DefaultClause {
            get {
                return ResourceManager.GetString("TemplateNode_DefaultClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string TemplateNode_DeleteStatement {
            get {
                return ResourceManager.GetString("TemplateNode_DeleteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else.
        /// </summary>
        internal static string TemplateNode_ElseClause {
            get {
                return ResourceManager.GetString("TemplateNode_ElseClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else if.
        /// </summary>
        internal static string TemplateNode_ElseIfClause {
            get {
                return ResourceManager.GetString("TemplateNode_ElseIfClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression.
        /// </summary>
        internal static string TemplateNode_Expression {
            get {
                return ResourceManager.GetString("TemplateNode_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreach clause.
        /// </summary>
        internal static string TemplateNode_ForeachClause {
            get {
                return ResourceManager.GetString("TemplateNode_ForeachClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreach.
        /// </summary>
        internal static string TemplateNode_ForeachStatement {
            get {
                return ResourceManager.GetString("TemplateNode_ForeachStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forfiles.
        /// </summary>
        internal static string TemplateNode_ForfilesStatement {
            get {
                return ResourceManager.GetString("TemplateNode_ForfilesStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string TemplateNode_FromClause {
            get {
                return ResourceManager.GetString("TemplateNode_FromClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if.
        /// </summary>
        internal static string TemplateNode_IfStatement {
            get {
                return ResourceManager.GetString("TemplateNode_IfStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string TemplateNode_InClause {
            get {
                return ResourceManager.GetString("TemplateNode_InClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert.
        /// </summary>
        internal static string TemplateNode_InsertStatement {
            get {
                return ResourceManager.GetString("TemplateNode_InsertStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit.
        /// </summary>
        internal static string TemplateNode_LimitClause {
            get {
                return ResourceManager.GetString("TemplateNode_LimitClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        internal static string TemplateNode_LogStatement {
            get {
                return ResourceManager.GetString("TemplateNode_LogStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model property.
        /// </summary>
        internal static string TemplateNode_ModelProperty {
            get {
                return ResourceManager.GetString("TemplateNode_ModelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output property.
        /// </summary>
        internal static string TemplateNode_OutputProperty {
            get {
                return ResourceManager.GetString("TemplateNode_OutputProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property/parameter.
        /// </summary>
        internal static string TemplateNode_Parameter {
            get {
                return ResourceManager.GetString("TemplateNode_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param.
        /// </summary>
        internal static string TemplateNode_ParamStatement {
            get {
                return ResourceManager.GetString("TemplateNode_ParamStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../.
        /// </summary>
        internal static string TemplateNode_PopContext {
            get {
                return ResourceManager.GetString("TemplateNode_PopContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to progress.
        /// </summary>
        internal static string TemplateNode_ProgressStatement {
            get {
                return ResourceManager.GetString("TemplateNode_ProgressStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string TemplateNode_RemoveStatement {
            get {
                return ResourceManager.GetString("TemplateNode_RemoveStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return.
        /// </summary>
        internal static string TemplateNode_ReturnStatement {
            get {
                return ResourceManager.GetString("TemplateNode_ReturnStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        internal static string TemplateNode_SortClause {
            get {
                return ResourceManager.GetString("TemplateNode_SortClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction.
        /// </summary>
        internal static string TemplateNode_SortDirectionClause {
            get {
                return ResourceManager.GetString("TemplateNode_SortDirectionClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch.
        /// </summary>
        internal static string TemplateNode_SwitchStatement {
            get {
                return ResourceManager.GetString("TemplateNode_SwitchStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.
        /// </summary>
        internal static string TemplateNode_Template {
            get {
                return ResourceManager.GetString("TemplateNode_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        internal static string TemplateNode_TemplateParameter {
            get {
                return ResourceManager.GetString("TemplateNode_TemplateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assignment.
        /// </summary>
        internal static string TemplateNode_TemplatePropertyAssignment {
            get {
                return ResourceManager.GetString("TemplateNode_TemplatePropertyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template/variable/parameter.
        /// </summary>
        internal static string TemplateNode_TemplateVariable {
            get {
                return ResourceManager.GetString("TemplateNode_TemplateVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this.
        /// </summary>
        internal static string TemplateNode_ThisContext {
            get {
                return ResourceManager.GetString("TemplateNode_ThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trace.
        /// </summary>
        internal static string TemplateNode_TraceStatement {
            get {
                return ResourceManager.GetString("TemplateNode_TraceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string TemplateNode_UpdateStatement {
            get {
                return ResourceManager.GetString("TemplateNode_UpdateStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var.
        /// </summary>
        internal static string TemplateNode_VarStatement {
            get {
                return ResourceManager.GetString("TemplateNode_VarStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where.
        /// </summary>
        internal static string TemplateNode_WhereClause {
            get {
                return ResourceManager.GetString("TemplateNode_WhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while.
        /// </summary>
        internal static string TemplateNode_WhileStatement {
            get {
                return ResourceManager.GetString("TemplateNode_WhileStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string TemplateNode_WithStatement {
            get {
                return ResourceManager.GetString("TemplateNode_WithStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be alphanumeric, or underscores, and not start with a number..
        /// </summary>
        internal static string Validation_AlphanumericValue {
            get {
                return ResourceManager.GetString("Validation_AlphanumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A base platform must be selected..
        /// </summary>
        internal static string Validation_BasePlatformCode {
            get {
                return ResourceManager.GetString("Validation_BasePlatformCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category name must be alaphanumeric..
        /// </summary>
        internal static string Validation_CategoryName {
            get {
                return ResourceManager.GetString("Validation_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A copyright name must be provided..
        /// </summary>
        internal static string Validation_Copyright {
            get {
                return ResourceManager.GetString("Validation_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A count greater than zero must be specified..
        /// </summary>
        internal static string Validation_Count {
            get {
                return ResourceManager.GetString("Validation_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data type must be selected..
        /// </summary>
        internal static string Validation_DataTypeCode {
            get {
                return ResourceManager.GetString("Validation_DataTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be alphanumeric, or underscores or ampersands, and can include spaces..
        /// </summary>
        internal static string Validation_DbNameValue {
            get {
                return ResourceManager.GetString("Validation_DbNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model object name &quot;{0}&quot; is a duplicate of another model object used in the current model(s)..
        /// </summary>
        internal static string Validation_DuplicateModelObjectFound {
            get {
                return ResourceManager.GetString("Validation_DuplicateModelObjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model property name &quot;{0}&quot; is a duplicate of another model property used in the current model object..
        /// </summary>
        internal static string Validation_DuplicateModelPropertyFound {
            get {
                return ResourceManager.GetString("Validation_DuplicateModelPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity must be selected..
        /// </summary>
        internal static string Validation_EntityID {
            get {
                return ResourceManager.GetString("Validation_EntityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_EntityName {
            get {
                return ResourceManager.GetString("Validation_EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity type must be selected..
        /// </summary>
        internal static string Validation_EntityTypeCode {
            get {
                return ResourceManager.GetString("Validation_EntityTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An enumeration must be selected..
        /// </summary>
        internal static string Validation_EnumerationID {
            get {
                return ResourceManager.GetString("Validation_EnumerationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A feature must be selected..
        /// </summary>
        internal static string Validation_FeatureID {
            get {
                return ResourceManager.GetString("Validation_FeatureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A feature name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_FeatureName {
            get {
                return ResourceManager.GetString("Validation_FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier type must be selected..
        /// </summary>
        internal static string Validation_IdentifierTypeCode {
            get {
                return ResourceManager.GetString("Validation_IdentifierTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An index must be selected..
        /// </summary>
        internal static string Validation_IndexID {
            get {
                return ResourceManager.GetString("Validation_IndexID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An index name must be alphanumeric, underscores, spaces, and not start with a number..
        /// </summary>
        internal static string Validation_IndexName {
            get {
                return ResourceManager.GetString("Validation_IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A length greater than zero must be specified..
        /// </summary>
        internal static string Validation_LengthInBits {
            get {
                return ResourceManager.GetString("Validation_LengthInBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be linked to an entity..
        /// </summary>
        internal static string Validation_LinkedEntityID {
            get {
                return ResourceManager.GetString("Validation_LinkedEntityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be linked to an entity..
        /// </summary>
        internal static string Validation_LinkedFeatureID {
            get {
                return ResourceManager.GetString("Validation_LinkedFeatureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be linked to an index..
        /// </summary>
        internal static string Validation_LinkedIndexID {
            get {
                return ResourceManager.GetString("Validation_LinkedIndexID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be linked to a method..
        /// </summary>
        internal static string Validation_LinkedMethodID {
            get {
                return ResourceManager.GetString("Validation_LinkedMethodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be linked to a parameter..
        /// </summary>
        internal static string Validation_LinkedParameterID {
            get {
                return ResourceManager.GetString("Validation_LinkedParameterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be linked to a property..
        /// </summary>
        internal static string Validation_LinkedPropertyID {
            get {
                return ResourceManager.GetString("Validation_LinkedPropertyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item must be linked to a relationship..
        /// </summary>
        internal static string Validation_LinkedRelationshipID {
            get {
                return ResourceManager.GetString("Validation_LinkedRelationshipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be alphanumeric, or underscores, and not start with a number, and can include spaces..
        /// </summary>
        internal static string Validation_LooseNameValue {
            get {
                return ResourceManager.GetString("Validation_LooseNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A metadata attribute must be selected..
        /// </summary>
        internal static string Validation_MedataAttributeCode {
            get {
                return ResourceManager.GetString("Validation_MedataAttributeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A meta attribute must be selected..
        /// </summary>
        internal static string Validation_MetaAttributeCode {
            get {
                return ResourceManager.GetString("Validation_MetaAttributeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A metadata attribute must be selected..
        /// </summary>
        internal static string Validation_MetadataAttributeCode {
            get {
                return ResourceManager.GetString("Validation_MetadataAttributeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method must be selected..
        /// </summary>
        internal static string Validation_MethodID {
            get {
                return ResourceManager.GetString("Validation_MethodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_MethodName {
            get {
                return ResourceManager.GetString("Validation_MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An order greater than zero must be specified..
        /// </summary>
        internal static string Validation_MethodRelationshipOrder {
            get {
                return ResourceManager.GetString("Validation_MethodRelationshipOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method type must be selected..
        /// </summary>
        internal static string Validation_MethodTypeCode {
            get {
                return ResourceManager.GetString("Validation_MethodTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cardinality value for {0} must be greater than zero or equal to -1 (-1 for many)..
        /// </summary>
        internal static string Validation_MinusOneOrMoreValue {
            get {
                return ResourceManager.GetString("Validation_MinusOneOrMoreValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  model must be selected..
        /// </summary>
        internal static string Validation_ModelID {
            get {
                return ResourceManager.GetString("Validation_ModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model object name &quot;{0}&quot; conflicts with a reserved word..
        /// </summary>
        internal static string Validation_ModelObjectReservedWordConflict {
            get {
                return ResourceManager.GetString("Validation_ModelObjectReservedWordConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model property name &quot;{0}&quot; conflicts with a reserved word..
        /// </summary>
        internal static string Validation_ModelPropertyReservedWordConflict {
            get {
                return ResourceManager.GetString("Validation_ModelPropertyReservedWordConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node must be selected..
        /// </summary>
        internal static string Validation_NodeName {
            get {
                return ResourceManager.GetString("Validation_NodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} (if provided) must be greater than or equal to 0..
        /// </summary>
        internal static string Validation_NonNegativeNumericValue {
            get {
                return ResourceManager.GetString("Validation_NonNegativeNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must not be null..
        /// </summary>
        internal static string Validation_NullValue {
            get {
                return ResourceManager.GetString("Validation_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object must be selected..
        /// </summary>
        internal static string Validation_ObjectID {
            get {
                return ResourceManager.GetString("Validation_ObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter must be selected..
        /// </summary>
        internal static string Validation_ParameterID {
            get {
                return ResourceManager.GetString("Validation_ParameterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_ParameterName {
            get {
                return ResourceManager.GetString("Validation_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter order in which the parameter will appear in the method signature must be greater than zero..
        /// </summary>
        internal static string Validation_ParameterOrder {
            get {
                return ResourceManager.GetString("Validation_ParameterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be alphanumeric, or underscores, -, or \\..
        /// </summary>
        internal static string Validation_PathNameValue {
            get {
                return ResourceManager.GetString("Validation_PathNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} must be provided, using only alphanumeric characters, underscores, (optionally separated by spaces) and / or :..
        /// </summary>
        internal static string Validation_PathValue {
            get {
                return ResourceManager.GetString("Validation_PathValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A platform must be selected..
        /// </summary>
        internal static string Validation_PlatformCode {
            get {
                return ResourceManager.GetString("Validation_PlatformCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be greater than 0..
        /// </summary>
        internal static string Validation_PositiveNumericValue {
            get {
                return ResourceManager.GetString("Validation_PositiveNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A precision greater than zero must be specified..
        /// </summary>
        internal static string Validation_Precision {
            get {
                return ResourceManager.GetString("Validation_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primary entity must be selected..
        /// </summary>
        internal static string Validation_PrimaryEntityID {
            get {
                return ResourceManager.GetString("Validation_PrimaryEntityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project name must be alphanumeric, underscores, can be space delimited, and cannot start with a number..
        /// </summary>
        internal static string Validation_ProjectName {
            get {
                return ResourceManager.GetString("Validation_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project namespace must be provided, using only alphanumeric characters, underscores, optionally separated by periods..
        /// </summary>
        internal static string Validation_ProjectNamespace {
            get {
                return ResourceManager.GetString("Validation_ProjectNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property must be selected..
        /// </summary>
        internal static string Validation_PropertyID {
            get {
                return ResourceManager.GetString("Validation_PropertyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_PropertyName {
            get {
                return ResourceManager.GetString("Validation_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property order greater than zero must be specified..
        /// </summary>
        internal static string Validation_PropertyOrder {
            get {
                return ResourceManager.GetString("Validation_PropertyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An order greater than zero must be specified..
        /// </summary>
        internal static string Validation_PropertyRelationshipOrder {
            get {
                return ResourceManager.GetString("Validation_PropertyRelationshipOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference entity must be selected..
        /// </summary>
        internal static string Validation_ReferencedEntityID {
            get {
                return ResourceManager.GetString("Validation_ReferencedEntityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primary property must be selected..
        /// </summary>
        internal static string Validation_ReferencedPropertyID {
            get {
                return ResourceManager.GetString("Validation_ReferencedPropertyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship must be selected..
        /// </summary>
        internal static string Validation_RelationshipID {
            get {
                return ResourceManager.GetString("Validation_RelationshipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_RelationshipName {
            get {
                return ResourceManager.GetString("Validation_RelationshipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship order greater than zero must be specified..
        /// </summary>
        internal static string Validation_RelationshipOrder {
            get {
                return ResourceManager.GetString("Validation_RelationshipOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scale greater than zero must be specified..
        /// </summary>
        internal static string Validation_Scale {
            get {
                return ResourceManager.GetString("Validation_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be selected..
        /// </summary>
        internal static string Validation_SelectedValue {
            get {
                return ResourceManager.GetString("Validation_SelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A diagram name must be alphanumeric, underscores, can be space delimited, and cannot start with a number..
        /// </summary>
        internal static string Validation_SolutionDiagramName {
            get {
                return ResourceManager.GetString("Validation_SolutionDiagramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solution must be selected..
        /// </summary>
        internal static string Validation_SolutionID {
            get {
                return ResourceManager.GetString("Validation_SolutionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solution name must be provided, using only alphanumeric characters, underscores, optionally separated by spaces..
        /// </summary>
        internal static string Validation_SolutionName {
            get {
                return ResourceManager.GetString("Validation_SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solution namespace must be provided, using only alphanumeric characters, underscores, optionally separated by periods..
        /// </summary>
        internal static string Validation_SolutionNamespace {
            get {
                return ResourceManager.GetString("Validation_SolutionNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database server name must be alphanumeric, underscores, dashes, dots, and can be space delimited..
        /// </summary>
        internal static string Validation_SourceDbName {
            get {
                return ResourceManager.GetString("Validation_SourceDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database name must be alphanumeric, underscores, dashes, dots, and can be space delimited..
        /// </summary>
        internal static string Validation_SourceDbServerName {
            get {
                return ResourceManager.GetString("Validation_SourceDbServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XML file name must be alphanumeric, underscores, dashes, dots, and can be space delimited..
        /// </summary>
        internal static string Validation_SourceFileName {
            get {
                return ResourceManager.GetString("Validation_SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A XML file path must be provided, using only alphanumeric characters, underscores, (optionally separated by spaces) and / or :..
        /// </summary>
        internal static string Validation_SourceFilePath {
            get {
                return ResourceManager.GetString("Validation_SourceFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specification order greater than zero must be specified..
        /// </summary>
        internal static string Validation_SpecificationOrder {
            get {
                return ResourceManager.GetString("Validation_SpecificationOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stage must be selected..
        /// </summary>
        internal static string Validation_StageID {
            get {
                return ResourceManager.GetString("Validation_StageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workflow stage name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_StageName {
            get {
                return ResourceManager.GetString("Validation_StageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stage order greater than zero must be specified..
        /// </summary>
        internal static string Validation_StageOrder {
            get {
                return ResourceManager.GetString("Validation_StageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stage transition name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_StageTransitionName {
            get {
                return ResourceManager.GetString("Validation_StageTransitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A state model must be selected..
        /// </summary>
        internal static string Validation_StateModelID {
            get {
                return ResourceManager.GetString("Validation_StateModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A state model name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_StateModelName {
            get {
                return ResourceManager.GetString("Validation_StateModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A state name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_StateName {
            get {
                return ResourceManager.GetString("Validation_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A state order greater than zero must be specified..
        /// </summary>
        internal static string Validation_StateOrder {
            get {
                return ResourceManager.GetString("Validation_StateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A state transition name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_StateTransitionName {
            get {
                return ResourceManager.GetString("Validation_StateTransitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workflow step name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_StepName {
            get {
                return ResourceManager.GetString("Validation_StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A step order greater than zero must be specified..
        /// </summary>
        internal static string Validation_StepOrder {
            get {
                return ResourceManager.GetString("Validation_StepOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A step transition name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_StepTransitionName {
            get {
                return ResourceManager.GetString("Validation_StepTransitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag can only contain alphanumeric characters and underscores..
        /// </summary>
        internal static string Validation_Tag {
            get {
                return ResourceManager.GetString("Validation_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template content must be provided and pass parsing..
        /// </summary>
        internal static string Validation_TemplateContent {
            get {
                return ResourceManager.GetString("Validation_TemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template name must be provided, using only alphanumeric characters, underscores, optionally separated by spaces..
        /// </summary>
        internal static string Validation_TemplateName {
            get {
                return ResourceManager.GetString("Validation_TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template output must pass parsing..
        /// </summary>
        internal static string Validation_TemplateOutput {
            get {
                return ResourceManager.GetString("Validation_TemplateOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template path must be provided, using only alphanumeric characters, underscores, (optionally separated by spaces) and / or :..
        /// </summary>
        internal static string Validation_TemplatePath {
            get {
                return ResourceManager.GetString("Validation_TemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tier must be selected..
        /// </summary>
        internal static string Validation_TierCode {
            get {
                return ResourceManager.GetString("Validation_TierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A visual studio version must be selected..
        /// </summary>
        internal static string Validation_VisualStudioVersionCode {
            get {
                return ResourceManager.GetString("Validation_VisualStudioVersionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workflow must be selected..
        /// </summary>
        internal static string Validation_WorkflowID {
            get {
                return ResourceManager.GetString("Validation_WorkflowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workflow name must be alphanumeric, underscores, and not start with a number..
        /// </summary>
        internal static string Validation_WorkflowName {
            get {
                return ResourceManager.GetString("Validation_WorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cardinality value for {0} must be greater than or equal to zero (0 for conditional)..
        /// </summary>
        internal static string Validation_ZeroOrMoreValue {
            get {
                return ResourceManager.GetString("Validation_ZeroOrMoreValue", resourceCulture);
            }
        }
    }
}
