//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoPlus.Interpreter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoPlus.Interpreter.Resources.ModelValues", typeof(ModelValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;ArrayOfDataType xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///&lt;DataType&gt;&lt;DataTypeCode&gt;1&lt;/DataTypeCode&gt;&lt;DataTypeName&gt;SByte&lt;/DataTypeName&gt;&lt;LengthInBits&gt;8&lt;/LengthInBits&gt;&lt;Description&gt;For signed byte data.&lt;/Description&gt;&lt;/DataType&gt;
        ///
        ///&lt;DataType&gt;&lt;DataTypeCode&gt;2&lt;/DataTypeCode&gt;&lt;DataTypeName&gt;Int Short&lt;/DataTypeName&gt;&lt;LengthInBits&gt;16&lt;/LengthInBits&gt;&lt;Description&gt;For short integer data.&lt;/Description&gt;&lt;/DataType&gt;
        ///
        ///&lt;DataType&gt;&lt;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataTypes {
            get {
                return ResourceManager.GetString("DataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;ArrayOfEntityType xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///&lt;EntityType&gt;&lt;EntityTypeCode&gt;1&lt;/EntityTypeCode&gt;&lt;EntityTypeName&gt;Lookup&lt;/EntityTypeName&gt;&lt;Description&gt;For lookup entities.&lt;/Description&gt;&lt;/EntityType&gt;
        ///
        ///&lt;EntityType&gt;&lt;EntityTypeCode&gt;2&lt;/EntityTypeCode&gt;&lt;EntityTypeName&gt;Lookup Business&lt;/EntityTypeName&gt;&lt;Description&gt;For key lookup entities that drive business rules.&lt;/Description&gt;&lt;/EntityType&gt;
        ///
        ///&lt;EntityType&gt;&lt;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityTypes {
            get {
                return ResourceManager.GetString("EntityTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;ArrayOfIdentifierType xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///&lt;IdentifierType&gt;&lt;IdentifierTypeCode&gt;1&lt;/IdentifierTypeCode&gt;&lt;IdentifierTypeName&gt;Generated&lt;/IdentifierTypeName&gt;&lt;Description&gt;For identifiers that are automatically generated.&lt;/Description&gt;&lt;/IdentifierType&gt;
        ///
        ///&lt;IdentifierType&gt;&lt;IdentifierTypeCode&gt;2&lt;/IdentifierTypeCode&gt;&lt;IdentifierTypeName&gt;Coded&lt;/IdentifierTypeName&gt;&lt;Description&gt;For identifiers that are  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IdentifierTypes {
            get {
                return ResourceManager.GetString("IdentifierTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;ArrayOfMethodType xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///&lt;MethodType&gt;&lt;MethodTypeCode&gt;1&lt;/MethodTypeCode&gt;&lt;MethodTypeName&gt;GetOne&lt;/MethodTypeName&gt;&lt;Description /&gt;&lt;/MethodType&gt;
        ///
        ///&lt;MethodType&gt;&lt;MethodTypeCode&gt;2&lt;/MethodTypeCode&gt;&lt;MethodTypeName&gt;GetAll&lt;/MethodTypeName&gt;&lt;Description /&gt;&lt;/MethodType&gt;
        ///
        ///&lt;MethodType&gt;&lt;MethodTypeCode&gt;3&lt;/MethodTypeCode&gt;&lt;MethodTypeName&gt;GetMany&lt;/MethodTypeName&gt;&lt;Description /&gt;&lt;/MethodType&gt;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodTypes {
            get {
                return ResourceManager.GetString("MethodTypes", resourceCulture);
            }
        }
    }
}
