//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoPlus.SolutionBuilder.WpfClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoPlus.SolutionBuilder.WpfClient.Resources.DisplayValues", typeof(DisplayValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo+ Code Template Documents (.mpt)|*.mpt.
        /// </summary>
        internal static string FileFilter_CodeTemplates {
            get {
                return ResourceManager.GetString("FileFilter_CodeTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images (.png,*.jpg,*.gif,*.ico)|.png;*.jpg;*.gif;*.ico.
        /// </summary>
        internal static string FileFilter_Images {
            get {
                return ResourceManager.GetString("FileFilter_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo+ Spec Template Documents (.mps)|*.mps.
        /// </summary>
        internal static string FileFilter_SpecTemplates {
            get {
                return ResourceManager.GetString("FileFilter_SpecTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Documents (.xml)|*.xml.
        /// </summary>
        internal static string FileFilter_XmlFiles {
            get {
                return ResourceManager.GetString("FileFilter_XmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents.
        /// </summary>
        internal static string Find_AllDocuments {
            get {
                return ResourceManager.GetString("Find_AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find Next.
        /// </summary>
        internal static string Find_ButtonFindNext {
            get {
                return ResourceManager.GetString("Find_ButtonFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.
        /// </summary>
        internal static string Find_ButtonReplace {
            get {
                return ResourceManager.GetString("Find_ButtonReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _All.
        /// </summary>
        internal static string Find_ButtonReplaceAll {
            get {
                return ResourceManager.GetString("Find_ButtonReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        internal static string Find_CaseSensitive {
            get {
                return ResourceManager.GetString("Find_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        internal static string Find_CurrentDocument {
            get {
                return ResourceManager.GetString("Find_CurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find And Replace.
        /// </summary>
        internal static string Find_FindAndReplace {
            get {
                return ResourceManager.GetString("Find_FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find_FindTab {
            get {
                return ResourceManager.GetString("Find_FindTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Find_Options {
            get {
                return ResourceManager.GetString("Find_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Find_ReplaceTab {
            get {
                return ResourceManager.GetString("Find_ReplaceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        internal static string Find_ReplaceWith {
            get {
                return ResourceManager.GetString("Find_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        internal static string Find_SearchIn {
            get {
                return ResourceManager.GetString("Find_SearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Up.
        /// </summary>
        internal static string Find_SearchUp {
            get {
                return ResourceManager.GetString("Find_SearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Find.
        /// </summary>
        internal static string Find_TextToFind {
            get {
                return ResourceManager.GetString("Find_TextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string Find_UseRegEx {
            get {
                return ResourceManager.GetString("Find_UseRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards.
        /// </summary>
        internal static string Find_UseWildcards {
            get {
                return ResourceManager.GetString("Find_UseWildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        internal static string Find_WholeWord {
            get {
                return ResourceManager.GetString("Find_WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Item.
        /// </summary>
        internal static string Message_CloseCaption {
            get {
                return ResourceManager.GetString("Message_CloseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this item that has outstanding changes?.
        /// </summary>
        internal static string Message_CloseItemConfirmation {
            get {
                return ResourceManager.GetString("Message_CloseItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  that has outstanding changes?.
        /// </summary>
        internal static string Message_ClosingItemEnd {
            get {
                return ResourceManager.GetString("Message_ClosingItemEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the tab .
        /// </summary>
        internal static string Message_ClosingItemIntro {
            get {
                return ResourceManager.GetString("Message_ClosingItemIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Solution.
        /// </summary>
        internal static string Message_ClosingSolutionCaption {
            get {
                return ResourceManager.GetString("Message_ClosingSolutionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been cancelled since there are open tabs for the solution..
        /// </summary>
        internal static string Message_ClosingSolutionEnd {
            get {
                return ResourceManager.GetString("Message_ClosingSolutionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closing of solution .
        /// </summary>
        internal static string Message_ClosingSolutionIntro {
            get {
                return ResourceManager.GetString("Message_ClosingSolutionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string Message_DeleteItemConfirmation {
            get {
                return ResourceManager.GetString("Message_DeleteItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string Message_DeleteItemConfirmationCaption {
            get {
                return ResourceManager.GetString("Message_DeleteItemConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item from the model?.
        /// </summary>
        internal static string Message_DeleteSelectedItem {
            get {
                return ResourceManager.GetString("Message_DeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all of the selected items from the model?.
        /// </summary>
        internal static string Message_DeleteSelectedItems {
            get {
                return ResourceManager.GetString("Message_DeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  could not be dropped.  An item of the same name was found at the drop target.  Please try again with a different drag source or drop target..
        /// </summary>
        internal static string Message_DropDuplicate {
            get {
                return ResourceManager.GetString("Message_DropDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping an item from another solution onto the diagram is not supported at this time.  Please drop items from other solutions into the model tree view first..
        /// </summary>
        internal static string Message_DropFromOtherSolution {
            get {
                return ResourceManager.GetString("Message_DropFromOtherSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  could not be dropped.  In order to copy, the drop target must be of the same type as the drag source, or the immediate parent to an item of the same type..
        /// </summary>
        internal static string Message_DropNotAllowed {
            get {
                return ResourceManager.GetString("Message_DropNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have opened a solution with the same SolutionID as an existing open solution.  This may cause unexpected results when editing.  Please close one of these solutions before editing..
        /// </summary>
        internal static string Message_DuplicateSolutions {
            get {
                return ResourceManager.GetString("Message_DuplicateSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has outstanding edits and must be closed.  Do you want to save the changes?.
        /// </summary>
        internal static string Message_ForceClosingItemEnd {
            get {
                return ResourceManager.GetString("Message_ForceClosingItemEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tab .
        /// </summary>
        internal static string Message_ForceClosingItemIntro {
            get {
                return ResourceManager.GetString("Message_ForceClosingItemIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string Message_IssueCaption {
            get {
                return ResourceManager.GetString("Message_IssueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have edited this item.  OK to lose changes?.
        /// </summary>
        internal static string Message_LoseEdits {
            get {
                return ResourceManager.GetString("Message_LoseEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Message_QuestionMarkEnd {
            get {
                return ResourceManager.GetString("Message_QuestionMarkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Item.
        /// </summary>
        internal static string Message_SaveCaption {
            get {
                return ResourceManager.GetString("Message_SaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Solution.
        /// </summary>
        internal static string Message_SaveSolutionCaption {
            get {
                return ResourceManager.GetString("Message_SaveSolutionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?  Cancel will abort closing the solution..
        /// </summary>
        internal static string Message_SaveSolutionChangesAbortEnd {
            get {
                return ResourceManager.GetString("Message_SaveSolutionChangesAbortEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?  Changes will be lost if you don&apos;t save..
        /// </summary>
        internal static string Message_SaveSolutionChangesLostEnd {
            get {
                return ResourceManager.GetString("Message_SaveSolutionChangesLostEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string Message_SaveSolutionFilter {
            get {
                return ResourceManager.GetString("Message_SaveSolutionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the solution .
        /// </summary>
        internal static string Message_SaveSolutionIntro {
            get {
                return ResourceManager.GetString("Message_SaveSolutionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution .
        /// </summary>
        internal static string Message_Solution {
            get {
                return ResourceManager.GetString("Message_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is closed..
        /// </summary>
        internal static string Message_SolutionClosed {
            get {
                return ResourceManager.GetString("Message_SolutionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string Message_SolutionFileExtension {
            get {
                return ResourceManager.GetString("Message_SolutionFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution must be saved to a file before generating code, please save and try again..
        /// </summary>
        internal static string Message_SolutionFileMustBeSaved {
            get {
                return ResourceManager.GetString("Message_SolutionFileMustBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait for the {0} job to complete prior to starting a new job..
        /// </summary>
        internal static string Thread_ThreadBusy {
            get {
                return ResourceManager.GetString("Thread_ThreadBusy", resourceCulture);
            }
        }
    }
}
